#!/usr/bin/env bash
# displays 'to infinity and beyond' with 'sleep 2' in btw each iteration
# 'I am invicible!!!' when receiving a SIGTERM signal

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invicible!!!"' SIGTERM
done
